### ISSUE TITLE
No module named 'colorama'

### ISSUE THREAD

**Issue by SeaN0X** [robert169/discord.py-selfbot#1]
when i execute the python script by cmd gives me this error

![image](https://user-images.githubusercontent.com/69431500/99702805-08ac9380-2a75-11eb-94ba-f4efb48ef3e3.png)

**Comment by SeaN0X** [comment]
Guys,I fixed this error
I put

pip install colorama 
on cmd and fixed,but it gives me a new error

No module named 'psutil'
![image](https://user-images.githubusercontent.com/69431500/99703165-8a9cbc80-2a75-11eb-87d5-059563f89cf4.png)

**Comment by robert169** [comment]
use pip install psutil

**Comment by SeaN0X** [comment]
Lol,Robert put a list of pips that need download to work
I will put all pips download here

pip install colorama
pip install psutil
pip install pyfiglet

after i install these 3 pips now its working fine

**Comment by robert169** [comment]
alright, i will do that for future projects, thank you
